### ISSUE TITLE
Making used contributorship taxonomy explicit

### ISSUE THREAD

**Issue by marton-balazs-kovacs** [tenzing-contrib/belayer#1]
To make the schema and the tenzing applications using it less dependent on using just one CRO (namely CRediT) currently we do not validate the role names within `role.name`.

Maybe we should add a metadata property to the `Role` schema that makes it explicit which CRO the given article uses. Then, we can even generate a sentence for the Authors' contribution section human-readable output stating which CRO was used and we can also add a citation to that CRO.

Also, this would allow for the validation of known CROs.

What do you think? @alexholcombe @mjaquiery

**Comment by mjaquiery** [comment]
That seems sensible to me. ✔️ 
I'd make the CRO optional, and support validation for it via a referenced JSON schema.

**Comment by alexholcombe** [comment]
👍 great

**Comment by marton-balazs-kovacs** [comment]
I do not think there are any cases where people use multiple CROTs. So I made a general property with the `name` and the `url` in the `metadata` object of the file. a83cf5d685d1a40ee06cf10760df0b9ef8d7eedc
